version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./www:/var/www

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php
      volumes:
        - ../www:/var/www/html
      expose:
        - "9000"
      depends_on:
        - mysql
        - redis
      restart: on-failure

### PHP-CLI Container #######################################

    php_cli:
      build:
        context: ./php_cli
      volumes:
        - ../www:/var/www/html
      depends_on:
        - mysql
        - redis
      tty: true
      restart: on-failure

### PHP-CLI_CRONTAB Container #######################################

    php_cli_crontab:
      build:
        context: ./php_cli_crontab
      volumes:
        - {WEB_ROOT}:/var/www/html
      depends_on:
        - mysql
        - redis
      tty: true
      restart: on-failure

### PHP-CLI_WORKER Container #######################################

    php_cli_worker:
      build:
        context: ./php_cli_worker
      volumes:
        - {WEB_ROOT}:/var/www/html
      depends_on:
        - mysql
        - redis
      tty: true
      restart: on-failure

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - ../www:/var/www/html
      ports:
          - "${NGINX_HTTP_PORT}:80"
          - "${NGINX_HTTPS_PORT}:443"
      depends_on:
          - php-fpm
      restart: on-failure

### MySQL Container #########################################

    mysql:
      image: mysql:5.7
      volumes:
          #- ../data/mysql:/var/lib/mysql
          - mysql_data:/var/lib/mysql
      expose:
        - 3306
#      ports:
#        - "${MYSQL_PORT}:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      restart: on-failure

### PHPMyAdmin Container #########################################

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "${PHPMYADMIN_PORT}:80"
      links:
          - mysql:db
      depends_on:
        - mysql
      restart: on-failure

### Redis Container #########################################

    redis:
      image: redis:3.2.11
      expose: 
        - "6379"
#      ports:
#        - "${REDIS_PORT}:6379"
      volumes:
        - ../data/redis:/data
      restart: on-failure

### Volumes Setup ###########################################

volumes:
  mysql_data:
networks:
  default:
    external:
      name: ${USER_NETWORK}
